### ISSUE TITLE
The "copyright 2020 created by Jake Lauer" watermark blends in with the box scores

### ISSUE THREAD

**Issue by n-fortunato** [BaseballTheater/BaseballTheater#24] opened 2020-03-06 04:34 UTC
For example: https://baseball.theater/game/_/606187/BoxScore

![image](https://user-images.githubusercontent.com/61859789/76052912-d3d5cc00-5f39-11ea-9e7b-a9ba11d13df0.png)

**Comment by jakelauer** [comment] 2020-03-06 06:37
Dupe of #20

**Closed as completed by jakelauer** 2020-03-06 06:37 UTC
