### ISSUE TITLE
Box Score trademark

### ISSUE THREAD

**Issue by robSanders818** [BaseballTheater/BaseballTheater#23] opened 2020-03-03 14:31 UTC
On box scores the trademark is showing up in the middle of the box score
![image](https://user-images.githubusercontent.com/45695926/75785460-c1894180-5d31-11ea-83d1-14a40f16f386.png)

**Comment by jakelauer** [comment] 2020-03-06 06:40
Dupe of #20

**Closed as completed by jakelauer** 2020-03-06 06:40 UTC
